name: Lint Workflows

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
  push:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@v1.7.7
        with:
          args: .github/workflows/lint-workflows.yml
